#!/usr/bin/env python3
"""Build the compact cold-start single-syllable dictionary asset."""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "ChinesePinyinIME" / "app" / "src" / "main" / "assets" / "pinyin_dict.txt"
OUTPUT = ROOT / "ChinesePinyinIME" / "app" / "src" / "main" / "assets" / "pinyin_syllable_dict.txt"
PINYIN_RE = re.compile(r"[a-z]{1,6}")
MAX_CANDIDATES = 20


def main() -> None:
    entries: list[tuple[str, list[str]]] = []
    for raw_line in SOURCE.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        pinyin, candidate_text = line.split("=", 1)
        pinyin = pinyin.strip()
        if PINYIN_RE.fullmatch(pinyin) is None:
            continue
        candidates = []
        seen = set()
        for candidate in candidate_text.split(","):
            candidate = candidate.strip()
            if len(candidate) != 1 or candidate in seen:
                continue
            seen.add(candidate)
            candidates.append(candidate)
            if len(candidates) >= MAX_CANDIDATES:
                break
        if candidates:
            entries.append((pinyin, candidates))

    lines = [
        "# ChinesePinyinIME compact single-syllable dictionary",
        "# Generated by scripts/build_syllable_dict.py from pinyin_dict.txt.",
        "# Do not edit manually; regenerate after changing the base dictionary.",
        "# Format: pinyin=single-character candidates",
        "#",
    ]
    lines.extend(f"{pinyin}={','.join(candidates)}" for pinyin, candidates in entries)
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"Wrote {len(entries)} syllables: {OUTPUT}")


if __name__ == "__main__":
    main()
